require:
 - rubocop-minitest
 - rubocop-rake
 - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6

Layout/LeadingCommentSpace:
  Enabled: false

Layout/LineContinuationLeadingSpace:
  Enabled: false

Layout/LineLength:
  # Enabled: false
  Max: 80
  # Max: 96
  # Max: 120

Lint/Debugger:
  Enabled: false

Lint/LiteralAsCondition:
  Enabled: false

Lint/RedundantSplatExpansion:
  Enabled: false

Lint/SafeNavigationChain:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

# Metrics/LayoutLength:
#   Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Minitest/MultipleAssertions:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  PreferredName: err

Security/Eval:
  Enabled: false

Security/YAMLLoad:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/CombinableLoops:
  Enabled: false

Style/CommentedKeyword:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/EmptyElse:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Style/IfUnlessModifier: # 2024-08 suggests lines that are too long
  Enabled: false

Style/KeywordParametersOrder:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/MixinUsage:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/MultilineIfModifier:
  Enabled: false

Style/OpenStructUse:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false

Style/PerlBackrefs: # Prefer ::Regexp.last_match.post_match over $'.
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/Semicolon: # Do not use semicolons to terminate expressions.
  Enabled: false

Style/SingleLineMethods: # Avoid single-line method definitions.
  Enabled: false

Style/SlicingWithRange:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: single_quotes

Style/UnlessElse:
  Enabled: false
