require:
 - rubocop-minitest
 - rubocop-rake
 - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6

Layout/LeadingCommentSpace:
  Enabled: false

Layout/LineContinuationLeadingSpace:
  Enabled: false

Layout/LineLength:
  Max: 96

Lint/Debugger:
  Enabled: false

Lint/SafeNavigationChain:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

# Metrics/LayoutLength:
#   Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Minitest/MultipleAssertions:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  PreferredName: err

Security/YAMLLoad:
  Enabled: false

Style/CommentedKeyword:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/EmptyElse:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Style/MixinUsage:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/SlicingWithRange:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: single_quotes
